//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.27 at 05:18:52 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://rs.tdwg.org/dwc/xsd/simpledarwincore/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package dwc.huh_harvard_edu.tdwg_dwc_simple;
