//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.27 at 05:18:52 PM EDT 
//


package dwc.huh_harvard_edu.tdwg_dwc_simple;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="Occurrence"/>
 *     &lt;enumeration value="Event"/>
 *     &lt;enumeration value="Location"/>
 *     &lt;enumeration value="Taxon"/>
 *     &lt;enumeration value="PreservedSpecimen"/>
 *     &lt;enumeration value="FossilSpecimen"/>
 *     &lt;enumeration value="LivingSpecimen"/>
 *     &lt;enumeration value="HumanObservation"/>
 *     &lt;enumeration value="MachineObservation"/>
 *     &lt;enumeration value="NomenclaturalChecklist"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TypeEnum", namespace = "http://rs.tdwg.org/dwc/dwctype/")
@XmlEnum
public enum TypeEnum {

    @XmlEnumValue("Occurrence")
    OCCURRENCE("Occurrence"),
    @XmlEnumValue("Event")
    EVENT("Event"),
    @XmlEnumValue("Location")
    LOCATION("Location"),
    @XmlEnumValue("Taxon")
    TAXON("Taxon"),
    @XmlEnumValue("PreservedSpecimen")
    PRESERVED_SPECIMEN("PreservedSpecimen"),
    @XmlEnumValue("FossilSpecimen")
    FOSSIL_SPECIMEN("FossilSpecimen"),
    @XmlEnumValue("LivingSpecimen")
    LIVING_SPECIMEN("LivingSpecimen"),
    @XmlEnumValue("HumanObservation")
    HUMAN_OBSERVATION("HumanObservation"),
    @XmlEnumValue("MachineObservation")
    MACHINE_OBSERVATION("MachineObservation"),
    @XmlEnumValue("NomenclaturalChecklist")
    NOMENCLATURAL_CHECKLIST("NomenclaturalChecklist");
    private final String value;

    TypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeEnum fromValue(String v) {
        for (TypeEnum c: TypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
